# Generated by Django 3.0 on 2020-11-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='AccountList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Никнейм')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Медиа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('post_url', models.CharField(max_length=5000, verbose_name='Ссылка на пост')),
                ('post_id', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='ID')),
                ('account', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='insta.Account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ('-date',),
            },
        ),
    ]
